version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio_vr
    volumes:
      - postgres_data:/var/lib/postgresql/data


  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    container_name: nestjs_backend
    volumes:
      - ./api:/usr/src/app
    command: npm run start:dev

  front:
    build: ./front
    container_name: angular_frontend
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - ./front:/usr/src/app
    command: npm start

volumes:
  postgres_data:
